name: gamorrah
description: "Game tracking application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  get:
  file_picker: ^6.1.1
  fluent_ui: ^4.4.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_launcher_icons: ^0.13.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.0
  reorderables: ^0.6.0
  system_theme: ^2.3.1
  uuid: ^4.0.5
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  hive_generator: ^2.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
